### ISSUE TITLE
letsencrypt-setup python error

### ISSUE THREAD

**Issue by brendaniel** [ngineered/nginx-php-fpm#164]
![image](https://user-images.githubusercontent.com/11773683/29265154-da38e7e4-811a-11e7-9e7a-04f253b79743.png)

bash-4.3# cat /tmp/tmpPRk2sp 
2017-08-14 09:02:48,151:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 733, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python2.7/site-packages/certbot/plugins/disco.py", line 203, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/disco.py", line 50, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2315, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (idna 2.6 (/usr/lib/python2.7/site-packages), Requirement.parse('idna<2.6,>=2.5'), set(['requests']))

**The above error prevents letsencrypt from running.**

**Comment by richarvey** [comment]
I'll take a look at this asap

**Comment by brendaniel** [comment]
@richarvey I think the version of the idna package is too high.

![image](https://user-images.githubusercontent.com/11773683/29274876-40c6ab26-8144-11e7-9c50-efd2c2e4fba0.png)

Can you control this in the Dockerfile?

**Comment by richarvey** [comment]
I'm wondering if something has been fixed upstream as i can't recreate the errors on certbot 0.17.0

```bash-4.3# certbot --version
certbot 0.17.0```

```bash-4.3# pip list  --format=columns | grep idna
idna           2.6```

**Comment by brendaniel** [comment]
I'm wondering what happens if I do not modify the Dockerfile or add something to the upstream.

Next time I upload the container, I'll check the idna version and upload it. (version of Python packages too)
